version: '2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "8888:8888"
    volumes:
      - .:/opt/app
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "db"
      POSTGRES_USER: "db"
      POSTGRES_DB: "blocks"
    ports:
      - "5432:5432"