version: '2'

services:
  api:
    container_name: blocks-api
    build:
      context: .
      dockerfile: Dockerfile
    command: node index.js
    env:
      - CONFIG=./config/dev.json
    ports:
      - "8888:8888"
    volumes:
      - .:/opt/app
    links:
      - db
  db:
    container_name: blocks-db
    image: coreykruger/blocks-db
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"